# Generated by Django 6.1 on 2026-08-23 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Guruh nomi')),
                ('slug', models.SlugField(unique=True)),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_ip', models.CharField(default='novamc.uz', max_length=100, verbose_name='Server IP manzili')),
                ('server_version', models.CharField(default='1.16.5 - 1.20+', max_length=50, verbose_name='Server versiyasi')),
                ('online_players_text', models.CharField(default="245 O'yinchi onlayn", max_length=100, verbose_name="Onlayn o'yinchilar matni")),
                ('payment_card_number', models.CharField(default='8800 5122 5832 6811', max_length=30, verbose_name="To'lov karta raqami")),
                ('payment_card_owner', models.CharField(blank=True, max_length=100, verbose_name='Karta egasi (ixtiyoriy)')),
                ('telegram_username', models.CharField(default='novamc_admin', max_length=100, verbose_name='Telegram username (@ siz)')),
                ('is_shop_open', models.BooleanField(default=True, help_text="O'chirilsa, saytda xarid formasi vaqtincha yopiladi", verbose_name="Do'kon ochiqmi?")),
            ],
            options={
                'verbose_name': 'Sayt sozlamasi',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True)),
                ('price', models.IntegerField(verbose_name='Narxi (UZS)')),
                ('commands', models.TextField(blank=True, help_text='Har bir buyruqni yangi qatorga yozing. Masalan: /kit askar', verbose_name='Buyruqlar')),
                ('features', models.TextField(blank=True, help_text='Har bir imkoniyatni yangi qatorga yozing. Masalan: Homelar soni: 4', verbose_name='Imkoniyatlar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Tovar',
                'verbose_name_plural': 'Tovarlar',
                'ordering': ['-price'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_nick', models.CharField(max_length=50, verbose_name="O'yinchi niki")),
                ('email', models.EmailField(max_length=254, verbose_name='Email manzil')),
                ('receipt_image', models.ImageField(upload_to='receipts/', verbose_name="To'lov cheki")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('delivered', 'Yetkazilgan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20, verbose_name='Holat')),
                ('admin_note', models.TextField(blank=True, help_text="Ichki izoh (faqat adminlar ko'radi)", verbose_name='Admin izohi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.product', verbose_name='Tovar')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
