# Generated by Django 6.1 on 2026-08-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_seed_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='discord_url',
            field=models.URLField(default='https://discord.gg/yswhhQKdB', verbose_name='Discord havolasi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_username',
            field=models.CharField(default='NovaMc_org', max_length=100, verbose_name='Telegram username (@ siz)'),
        ),
    ]
