# Generated by Django 6.1 on 2026-08-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_sitesettings_discord_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, verbose_name='Sessiya ID')),
                ('user_nick', models.CharField(default='Mehmon', max_length=100, verbose_name='Foydalanuvchi niki')),
                ('sender', models.CharField(choices=[('user', 'Foydalanuvchi'), ('admin', 'Admin')], default='user', max_length=10, verbose_name='Yuboruvchi')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('is_read_by_admin', models.BooleanField(default=False, verbose_name="Admin o'qidimi?")),
                ('is_read_by_user', models.BooleanField(default=False, verbose_name="Foydalanuvchi o'qidimi?")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
            ],
            options={
                'verbose_name': 'Chat xabari',
                'verbose_name_plural': 'Chat xabarlari',
                'ordering': ['created_at'],
            },
        ),
    ]
