# Generated by Django 6.0.6 on 2026-09-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_admin_chat_id',
            field=models.CharField(blank=True, help_text='Xaridlarni qabul qiluvchi adminning chat ID si (yoki guruh ID si)', max_length=100, null=True, verbose_name='Admin Telegram Chat ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_bot_token',
            field=models.CharField(blank=True, help_text="BotFather'dan olingan token (masalan: 123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11)", max_length=255, null=True, verbose_name='Telegram Bot Token'),
        ),
    ]
