# Generated by Django 5.2.17 on 2026-09-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_sitesettings_telegram_admin_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email manzil'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_admin_chat_id',
            field=models.CharField(blank=True, help_text='Xaridlarni qabul qiluvchi adminning chat ID si (yoki guruh ID si)', max_length=100, null=True, verbose_name='8997272977'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_bot_token',
            field=models.CharField(blank=True, help_text="BotFather'dan olingan token (masalan: 123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11)", max_length=255, null=True, verbose_name='8822514489:AAGH5ZsrMPNe0KdjOZm9pSFdzAkgxs3UUz4'),
        ),
    ]
