# Generated by Django 5.2.17 on 2026-09-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_order_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minecraft_nick', models.CharField(max_length=100, unique=True, verbose_name='Minecraft Niki')),
                ('code', models.CharField(max_length=6, verbose_name='Tasdiqlash Kodi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Ulanish Kodi',
                'verbose_name_plural': 'Ulanish Kodlari',
            },
        ),
        migrations.CreateModel(
            name='PlayerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=100, unique=True, verbose_name='Telegram ID')),
                ('minecraft_nick', models.CharField(max_length=100, unique=True, verbose_name='Minecraft Niki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ulangan vaqt')),
            ],
            options={
                'verbose_name': 'Ulangan Akkaunt',
                'verbose_name_plural': 'Ulangan Akkauntlar',
            },
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_bot_token',
            field=models.CharField(blank=True, help_text="BotFather'dan olingan token (masalan: 123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11)", max_length=255, null=True, verbose_name='8980335834:AAFNNx5vuxShDk6xrVxtuSw_siinTOw_IE8'),
        ),
    ]
