# Generated by Django 6.0.6 on 2026-09-06 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_linkcode_playeraccount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Server nomi')),
                ('slug', models.SlugField(unique=True)),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Serverlar',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shop.servermode', verbose_name='Server'),
        ),
    ]
