# Generated by Django 5.2.17 on 2026-09-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_servermode_category_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_bot_token',
            field=models.CharField(blank=True, help_text="BotFather'dan olingan token (masalan: 123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11)", max_length=255, null=True, verbose_name='8822514489:AAGH5ZsrMPNe0KdjOZm9pSFdzAkgxs3UUz4'),
        ),
    ]
